### DISCUSSION TITLE
Dependency issues

### DISCUSSION THREAD

**Discussion by FilipeOS** [renggli/dart-xml#161] [Q&A] [answered]
Hi there,

Can someone please advise me why this is happening and help me point to the right direction?

Basically I had to updgrade the entire app and this is pissing me off:

```
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  package_info: ^2.0.2
  intl: ^0.17.0
  fluttertoast: ^8.1.1
  google_maps_flutter: ^2.2.1
  xml: ^6.2.2
  http: ^0.13.5
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  json_serializable: ^6.5.4
  flutter_native_splash: ^2.2.14
```

Flutter and dart is updated properly.

I get this issue:
```
Because xml >=6.2.0 depends on collection ^1.17.0 and every version of flutter from sdk depends on collection 1.16.0, xml >=6.2.0 is incompatible with flutter from sdk.
So, because bcppark depends on both flutter from sdk and xml ^6.2.2, version solving failed.
pub get failed (1; So, because bcppark depends on both flutter from sdk and xml ^6.2.2, version solving failed.)
```
